### ISSUE TITLE
Add an Appropriate Icon

### ISSUE THREAD

**Issue by suraj-fusion** [suraj-fusion/Solarify-India#1]
Add a icon related to solar energy.You can add any icon present on the internet or you can get creative and create a custom icon and add it to the site.

**Comment by afzalzbr** [comment]
Hi, please assign this issue to me, I can work on it.

**Comment by real-coder007Ravi** [comment]
I want to work on this issue.could u please assign it to me

**Comment by suraj-fusion** [comment]
> I want to work on this issue.could u please assign it to me

This project is especially made for Hackcodex event ..my college is organizing to help beginners understand open source contributions have u registered for the event if not please check the readme section of the project

**Comment by real-coder007Ravi** [comment]
Yes I have registered for the event, and I am new to Open Source Contributions. I want to work on this issue in order to understand Open source in a better way
