### ISSUE TITLE
Add a new Route 

### ISSUE THREAD

**Issue by suraj-fusion** [suraj-fusion/Solarify-India#13]
Add a new route to "Go Solar" option on navigation bar and redirect it to "https://mnre.gov.in/solar/current-status/" this site

**Comment by suraj-fusion** [comment]
@real-coder007Ravi

**Comment by real-coder007Ravi** [comment]
#14

**Comment by real-coder007Ravi** [comment]
Can u please assign 5-6 more issues to me so that I can strengthen my skills and collaborate more on the project.
