### ISSUE TITLE
Add appropriate styles to the navigation bar

### ISSUE THREAD

**Issue by suraj-fusion** [suraj-fusion/Solarify-India#2]
Add some styles(colors) to the navigation bar try to keep it as minimalistic as possible

**Comment by afzalzbr** [comment]
Please assign this issue to me for working on it.

**Comment by real-coder007Ravi** [comment]
I want to work on this issue. Could u please assign it to me

**Comment by real-coder007Ravi** [comment]
#9

**Comment by real-coder007Ravi** [comment]
Now please check made with my account from where i am actually creating a pull request that is @real-coder007Ravi 
Please see the pull request #10
