### ISSUE TITLE
Add an Image of Solar Panels

### ISSUE THREAD

**Issue by suraj-fusion** [suraj-fusion/Solarify-India#4]
Add an image of Solar panels on the home section and position it such that it looks good

**Comment by real-coder007Ravi** [comment]
I want to work on this issue, could u please assign it to me.

**Comment by real-coder007Ravi** [comment]
#5

**Comment by suraj-fusion** [comment]
I did not ask to add the image as background rather add the image using image tag before the text 
and consider using a better image without any links.Although i merged your PR open another PR with the appropriate changes

**Comment by Ravi-developer246383** [comment]
It is not showing any pull requests yet on my profile.can u please tell why it is not showing any pull requests made although I made 2 PRs

**Comment by suraj-fusion** [comment]
have u registered (on hackodex) and logged in from the same account from which you are making pull request.. i noticed u are using two different accounts.
